### ISSUE TITLE
Consider pre-commit-ci/lite

### ISSUE THREAD

**Issue by jl-wynen** [scipp/copier_template#104]
If I understand correctly, we could use https://github.com/pre-commit-ci/lite-action instead of the autocommit action to apply changes to PRs. This may work better than the current approach which creates a separate commit but doesn't run CI on it. 
We'd still have to run pre-commit ourselves.

**Comment by jl-wynen** [comment]
I just installed it for essnmx.

**Comment by YooSunYoung** [comment]
Here is what I tested in ``essnmx``: https://github.com/scipp/essnmx/pull/12.

## Applied wrong format on purpose and pre-commit fixed them
![image](https://github.com/scipp/copier_template/assets/17974113/9fef87d0-6b12-4da1-8101-066561464295)

## Pre-commit CI made a commit with fixes
![image](https://github.com/scipp/copier_template/assets/17974113/ce58eef6-6470-42b1-8688-24a89d27723c)

## Final CI tests passes!
![image](https://github.com/scipp/copier_template/assets/17974113/923712e7-b179-4025-baa2-adfd45be65a7)

**Comment by YooSunYoung** [comment]
I think it's very neat and we should use this one instead.
First we need to install them for all repositories I guess, 
and then I can make the change here.

**Comment by jl-wynen** [comment]
And it actually ran the CI pipeline on the new commit!

I'm happy with it, any objections @scipp/scipp-maintainers ?
