### ISSUE TITLE
Run linkcheck

### ISSUE THREAD

**Issue by jl-wynen** [scipp/copier_template#109]
There are no calls to linkcheck in the template in CI. This should be added to the docs workflow but not in PRs.

**Comment by SimonHeybrock** [comment]
Note that there is a tox env for this: https://github.com/scipp/copier_template/blob/ff7f76be4a02a021e522568892ab82c89d2aaf93/template/tox.ini.jinja#L41-L44

**Comment by jl-wynen** [comment]
What was the reason for not running linkcheck in CI during PR? Was it only performance? In this case, should we just reenable it? Most projects don't have many links. And we tend to be slow to fix broken links when detected in main builds.

**Comment by SimonHeybrock** [comment]
> What was the reason for not running linkcheck in CI during PR? Was it only performance?

Not at all. It was due to frequent issues with flakyness, e.g., when a site is temporarily unreachable.
