### ISSUE TITLE
Change pre-commit `check-added-large-files` size limit?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/copier_template#122]
See recent accidental merge of a 80 kByte binary file into `esssans@main`. The default is 500 kByte. Is this good, or do we want to consider lowering it?

**Comment by jl-wynen** [comment]
Do you know the max size of code files in our projects?

**Comment by YooSunYoung** [comment]
> Do you know the max size of code files in our projects?


essnmx
- essnmx/docs/conf.py 6848
scippnexus
- scippnexus/tests/nxdetector_test.py 32728
scippneutron
- scippneutron/tests/io/load_nexus_test.py 73998
scipp
- scipp/lib/variable/test/variable_test.cpp 42108
essimaging
- essimaging/docs/conf.py 6884
ess
- ess/src/ess/sans/beam_center_finder.py 15137
essreflectometry
- essreflectometry/src/essreflectometry/logging.py 10600
beamlime
- beamlime/src/beamlime/constructors/providers.py 22477
plopp
- plopp/src/plopp/backends/matplotlib/canvas.py 15111
esssans
- esssans/src/esssans/beam_center_finder.py 16077
sciline
- sciline/src/sciline/pipeline.py 28904

I just filtered all files with ``('.py', '.md', '.txt', '.cpp', '.hpp', '.h', '.sh')`` extensions.

So... among these files in the repositories listed above,
maximum code file size is around 73 KB...??

**Comment by jl-wynen** [comment]
> maximum code file size is around 73 KB...??

So we can't really disallow adding a 80kB file.

Is the issue more about disallowing binary files? But then we need a way to circumvent the check for images...

**Comment by SimonHeybrock** [comment]
So maybe the conclusion is that we should leave it as it is?
