### ISSUE TITLE
CI suddenly fails without changes

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/copier_template#148]
Fails with "ModuleNotFoundError: No module named 'yamlinclude'".

See rerun of old (passing) CI run: https://github.com/scipp/copier_template/actions/runs/8293977426/job/23375827479. This also happens, e.g., with a new PR.

**Comment by jl-wynen** [comment]
It's a dependency problem with copier: https://github.com/copier-org/copier/issues/1568

**Comment by SimonHeybrock** [comment]
Isn't it pinned, as we typically do?
