### ISSUE TITLE
Should docs/_templates/doc_version.html be a jinja template?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/copier_template#186]
Something looks broken, not sure what. See, e.g., https://scipp.github.io/esssans/.

**Comment by jl-wynen** [comment]
The link to older versions does not work.
But can you be more precise about what looks wrong?

**Comment by SimonHeybrock** [comment]
I think the orgname is missing? My guess was that since the jinja template is missing copier does not render the template. Instead it is rendered by Sphinx, which does not have all the variables (but happens to have the project name)?
