### ISSUE TITLE
Attach documentation to releases

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/copier_template#21]
See scipp/plopp#238. Wait until we have another plopp release to ensure it works.

Also:
- Add version visible in docs.
- Add a link in docs where to find docs for old releases.

**Comment by nvaytet** [comment]
> Add version visible in docs.

For this, I think we can add the current version to the footer by doing something like `"footer_start": ["copyright", "sphinx-version", "doc_version"],` in the `docs/conf.py` file.

> Add a link in docs where to find docs for old releases.

Not sure where that one should go. Might make sense next to the current version in the footer, but then maybe it is not so visible? I also thought of using the version selection menu which would just have two entries: the current version and a link to "older versions".
But I am not sure how that would work with respect to being automatically updated on a new release.
It would however have the benefit of being more visible, in the top bar of the page.

@jl-wynen any ideas/opinions?

**Comment by SimonHeybrock** [comment]
Maybe add it in an `About` section, similar to how you have it in Plopp?

**Comment by nvaytet** [comment]
I have put this in the footer. I will also add a note on where to find the other versions in an About page.
![Screenshot at 2023-09-15 13-59-38](https://github.com/scipp/copier_template/assets/39047984/573b11dc-ce0f-4422-a262-df7eca8204ea)
