### ISSUE TITLE
Consider switching to ruff

### ISSUE THREAD

**Issue by jl-wynen** [scipp/copier_template#70]
[Ruff](https://docs.astral.sh/ruff/) is similar to flake8 but faster and it has a lot of plugins built in. It does not have full parity with flake8 but in my experience with Scitacean is close enough. It also includes reimplementations of isort and bandit. So switching to it would allow us to handle fewer dependencies (1 instead of 4).

We can then also go through the list of rules and activate additional ones. See e.g. https://github.com/SciCatProject/scitacean/blob/f2c52f5a1bceb3155c4907d76d60c9ada2f58aa8/pyproject.toml#L100-L126 which is working well for be but is rather strict.

There is also an experimental code formatter that tries to be compatible with black as much as possible. An advantage of it would be that it allows us to customise the quotation mark style. I.e., we can make it use single quotes everywhere. So we can normalise the quotes instead of leaving it up to the developer as we do right now. If we want to.

Also, ruff has support for linting and formatting notebooks. I have not tried it though.

**Comment by SimonHeybrock** [comment]
> So we can normalise the quotes instead of leaving it up to the developer as we do right now. If we want to.

We have this explicitly disabled right now because we did not want to.

**Comment by jl-wynen** [comment]
Yes. I brought this up to see if the opinion has changed. In particular if for someone this was based in not liking double quotes. I personally just like not having to think about it.

**Comment by jl-wynen** [comment]
Since it's starting to annoy me how long it takes to make commits, I did a quick benchmark. When committing `mantid.py` in scippneutron, I get these times for `time git commit`:
```
flake8 + flake8-plugins + isort + black: 1.8s
ruff + black: 1.0s
ruff + ruff-format: 0.9s
```

This is of course not representative of all codebases or files. And 2s is not that long anyway.

**Comment by MridulS** [comment]
Not to ruffle (pun intedended) too many things here, but I think it makes sense to just start using ruff all across and forget about it. It has pretty decent defaults and covers code, jupyter notebooks and even enforcing doc style standards.

**Comment by jl-wynen** [comment]
Has been merged into Scipp and the Copier template. But rolling out the template also rolls out the copier-update-bot. So this needs more testing and is going slowly. But this will now happen regardless. So I'm closing this issue as done.
